apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-crud-api
  labels:
    app: node-crud-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-crud-api
  template:
    metadata:
      labels:
        app: node-crud-api
    spec:
      containers:
      - name: node-crud-api
        imagePullPolicy: Always
        image: fractalxv/js-crud-api:v3
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-crud-api
  labels:
    app: node-crud-api
spec:
  selector:
    app: node-crud-api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-crud-api-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    acme.cert-manager.io/http01-edit-in-place: "true"
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - api.myra.lyr.id
    secretName: myra-node-crud-api-v3
  rules:
  - host: api.myra.lyr.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node-crud-api
            port:
              name: http